### ISSUE TITLE
Notes

### ISSUE THREAD

**Issue by satouriko** [Zack-Bee/Li-Translate#1]
+ node_modules 应该是忽略的（带着这么大的东西提交你不累么）
+ Li-Translate.crx、Li-Translate.zip 这种东西应该放到 release 里，不是源码里
+ LICENSE 既然单独有一个文件就不用把这么长的东西放 readme 里了 想放的话放[这一点](https://www.gnu.org/licenses/gpl-howto.en.html)就可以了
```
    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Lesser General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
```
+ GNU LESSER GENERAL PUBLIC LICENSE 是 LGPL 不是 GPL
+ 你 Google 上的这个zackbee.geek链接有问题QwQ
![image](https://user-images.githubusercontent.com/18373361/31307311-6cffda4e-ab94-11e7-848a-71137328590e.png)

**Comment by Zack-Bee** [comment]
尴尬，写了gitignore忘了add了
第三点我看到另外一个人是这样将license加入到readme的以为这样是规范
第四点我弄混淆了。。。QwQ
那个链接似乎是自动生成的，我等会把以上的问题改一下
感谢jiahao的建议QwQ

**Comment by satouriko** [comment]
https://github.com/Zack-Bee/Li-Translate/commit/c63ab07cf90b434008f747b7c3988dc492647643#commitcomment-24841039
